"""empty message

Revision ID: 888f996a898e
Revises: d41d0fb21430
Create Date: 2020-04-10 15:27:37.344922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '888f996a898e'
down_revision = 'd41d0fb21430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Artist_Genres')
    op.drop_table('Venue_Genres')
    op.drop_table('Genre')
    op.add_column('Artist', sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('Venue', sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    op.create_table('Genre',
    sa.Column('id_genre', sa.INTEGER(), server_default=sa.text('nextval(\'"Genre_id_genre_seq"\'::regclass)'), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_genre', name='Genre_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Venue_Genres',
    sa.Column('id_venue', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_genre', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_genre'], ['Genre.id_genre'], name='Venue_Genres_id_genre_fkey'),
    sa.ForeignKeyConstraint(['id_venue'], ['Venue.id'], name='Venue_Genres_id_venue_fkey'),
    sa.PrimaryKeyConstraint('id_venue', 'id_genre', name='Venue_Genres_pkey')
    )
    op.create_table('Artist_Genres',
    sa.Column('id_artist', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_genre', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_artist'], ['Artist.id'], name='Artist_Genres_id_artist_fkey'),
    sa.ForeignKeyConstraint(['id_genre'], ['Genre.id_genre'], name='Artist_Genres_id_genre_fkey'),
    sa.PrimaryKeyConstraint('id_artist', 'id_genre', name='Artist_Genres_pkey')
    )
    # ### end Alembic commands ###
