"""empty message

Revision ID: d41d0fb21430
Revises: 8d327a999a67
Create Date: 2020-04-10 13:26:38.151956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41d0fb21430'
down_revision = '8d327a999a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
    sa.Column('id_genre', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_genre')
    )
    op.create_table('Artist_Genres',
    sa.Column('id_artist', sa.Integer(), nullable=False),
    sa.Column('id_genre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_artist'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['id_genre'], ['Genre.id_genre'], ),
    sa.PrimaryKeyConstraint('id_artist', 'id_genre')
    )
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_venue', sa.Integer(), nullable=False),
    sa.Column('id_artist', sa.Integer(), nullable=False),
    sa.Column('show_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_artist'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['id_venue'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Venue_Genres',
    sa.Column('id_venue', sa.Integer(), nullable=False),
    sa.Column('id_genre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_genre'], ['Genre.id_genre'], ),
    sa.ForeignKeyConstraint(['id_venue'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id_venue', 'id_genre')
    )
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_table('Venue_Genres')
    op.drop_table('Show')
    op.drop_table('Artist_Genres')
    op.drop_table('Genre')
    # ### end Alembic commands ###
